# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        perl: ['5.20', '5.22', '5.24', '5.26', '5.28', '5.30']

    container:
      image: perl:${{ matrix.perl-version }}

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Fix ExtUtils::MakeMaker (for Perl 5.16 and 5.18)
      run: cpanm -n App::cpanminus ExtUtils::MakeMaker

    - name: Install dependencies
      run: |
        cpanm -n --installdeps .
        cpanm -n Test::Pod Test::Pod::Coverage

    - name: Run tests
      run: prove -l t/ xt/
